language: java

jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk10
- oraclejdk-ea
- openjdk8

install: true
sudo: false

before_script:
- pip install --user codecov

after_success:
- bash <(curl -s https://codecov.io/bash)