sudo: false

language: java

matrix:
  include:
    - name: OpenJDK 8
      jdk: openjdk8
    - name: OpenJDK 11
      jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

dist: trusty

install:
  # https://github.com/travis-ci/travis-ci/issues/8408
  - unset _JAVA_OPTIONS

before_script:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)