language: java

jdk:
- oraclejdk8

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle

install: true
sudo: false

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)