language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk11
  - openjdk11
  - openjdk-ea
  - oraclejdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea oraclejdk-ea

dist: trusty

install: true
sudo: false

before_script:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)